#!/usr/bin/env python3
"""
SFT Fine-tuning: Search Result Reasoning Agent

Trains Ministral-3-3B-Instruct on CoT training data generated by
generate_cot_dataset.py. Uses QLoRA + completion-only loss masking
so the model learns to reason over search results in <think>...</think>
tags and produce structured JSON answers.

Usage:
    python train_search_reasoner.py \
        --hub_repo your-username/search-reasoner-3b \
        --wandb_project search-reasoner-3b
"""

import argparse
import json
import math
import os
import re
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch
from datasets import Dataset
from peft import LoraConfig, TaskType
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainerCallback,
    TrainerState,
    TrainingArguments,
)

_MINISTRAL_CLS = None
for _cls_name in ("Mistral3ForConditionalGeneration", "MinistralForCausalLM"):
    try:
        _MINISTRAL_CLS = getattr(__import__("transformers", fromlist=[_cls_name]), _cls_name)
        break
    except (ImportError, AttributeError):
        continue
from trl import SFTConfig, SFTTrainer

try:
    from trl import DataCollatorForCompletionOnlyLM
    _HAS_COMPLETION_COLLATOR = True
except ImportError:
    _HAS_COMPLETION_COLLATOR = False

# ──────────────────────────────────────────────
# 1. SYSTEM PROMPT (shared with generate_cot_dataset.py)
# ──────────────────────────────────────────────

SEARCH_REASONER_SYSTEM_PROMPT = """\
You are a Search Result Reasoning Agent. Your job is to analyze web search \
results and their scraped content to answer a user's question accurately.

## Process

You MUST think step-by-step inside <think>...</think> tags before giving \
your final answer. Your reasoning should:

1. **Evaluate each search result**: For each of the provided search results, assess:
   - Is the source credible and authoritative for this topic?
   - Does the title/snippet suggest it contains relevant information?
   - Does the scraped page content actually contain the answer?
   - Rate each result: HIGHLY_RELEVANT, SOMEWHAT_RELEVANT, or NOT_RELEVANT

2. **Identify answer-bearing results**: Which specific results contain \
information that directly answers the question? Quote the relevant passages.

3. **Cross-reference**: Do multiple sources agree? Are there contradictions? \
Which source is most trustworthy?

4. **Synthesize**: Combine information from the best sources into a coherent answer.

## Output Format

After your <think>...</think> reasoning, provide your answer in this exact JSON format:

```json
{
  "result_rankings": [
    {"rank": 1, "result_index": <0-indexed>, "relevance": "HIGHLY_RELEVANT", "reason": "..."},
    {"rank": 2, "result_index": <0-indexed>, "relevance": "SOMEWHAT_RELEVANT", "reason": "..."}
  ],
  "best_result_index": <0-indexed int>,
  "answer": "<LETTER>",
  "confidence": <0.0 to 1.0>,
  "supporting_evidence": ["<quote from source 1>", "<quote from source 2>"]
}
```

## Rules
- Always evaluate ALL results before deciding
- Prefer primary sources over secondary
- If no result contains a good answer, say so honestly
- Be specific — cite which result(s) informed your answer
- If the question is multiple-choice, state the letter answer clearly"""


# ──────────────────────────────────────────────
# 2. DATA LOADING
# ──────────────────────────────────────────────


def load_cot_dataset(path: str) -> Dataset:
    """Load the CoT training JSONL into a HuggingFace Dataset."""
    records = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    print(f"  Loaded {len(records)} records from {path}")
    return Dataset.from_list(records)


def format_to_messages(example: dict) -> dict:
    """Convert a CoT record into chat messages for the tokenizer."""
    user_content = f"## Question\n{example['question']}\n\n## Search Results\n{example['search_context']}"
    messages = [
        {"role": "system", "content": SEARCH_REASONER_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": example["teacher_response"]},
    ]
    return {"messages": messages}


def apply_chat_template(example: dict, tokenizer) -> dict:
    """Apply the tokenizer's chat template to produce a text field."""
    messages = example["messages"]
    try:
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
    except Exception:
        text = tokenizer.apply_chat_template(
            messages, tokenize=False
        )
    return {"text": text}


# ──────────────────────────────────────────────
# 3. RESPONSE TEMPLATE DETECTION
# ──────────────────────────────────────────────


def detect_response_template(tokenizer) -> str:
    """
    Auto-detect the token sequence marking assistant turn start.
    Used by DataCollatorForCompletionOnlyLM to mask loss on everything
    before the assistant's generated content.
    """
    marker = "___ASSISTANT_START_MARKER___"
    dummy_messages = [
        {"role": "user", "content": "Hello"},
        {"role": "assistant", "content": marker},
    ]
    try:
        rendered = tokenizer.apply_chat_template(
            dummy_messages, tokenize=False, add_generation_prompt=False
        )
    except Exception:
        rendered = tokenizer.apply_chat_template(dummy_messages, tokenize=False)

    marker_idx = rendered.find(marker)
    if marker_idx == -1:
        raise ValueError(
            f"Could not find marker in rendered template: {rendered[:200]}"
        )

    prefix = rendered[max(0, marker_idx - 50) : marker_idx]

    for start in range(len(prefix)):
        candidate = prefix[start:]
        if candidate.strip():
            before_marker = rendered[:marker_idx]
            if before_marker.count(candidate) == 1:
                return candidate

    fallback = prefix[-10:].strip()
    print(f"Warning: Using fallback response template: {repr(fallback)}")
    return fallback


# ──────────────────────────────────────────────
# 4. INFERENCE EVALUATION
# ──────────────────────────────────────────────


def parse_model_output(text: str) -> dict:
    """
    Parse a model's generated text for validity metrics.
    Returns dict with json_valid, schema_valid, parsed_answer.
    """
    result = {
        "json_valid": False,
        "schema_valid": False,
        "parsed_answer": None,
        "has_think_tags": "<think>" in text and "</think>" in text,
    }

    after_think = text
    if "</think>" in text:
        after_think = text.split("</think>", 1)[1].strip()

    json_match = re.search(r"\{[\s\S]*\}", after_think)
    if not json_match:
        return result

    try:
        parsed = json.loads(json_match.group())
        result["json_valid"] = True
    except json.JSONDecodeError:
        return result

    if "answer" in parsed and "best_result_index" in parsed:
        result["schema_valid"] = True
        answer = str(parsed["answer"]).strip().upper()
        if answer in ("A", "B", "C", "D"):
            result["parsed_answer"] = answer

    return result


@torch.no_grad()
def run_inference_eval(
    model,
    tokenizer,
    eval_dataset,
    max_examples: int = 50,
    max_new_tokens: int = 1024,
    desc: str = "eval",
) -> tuple[dict, list[dict]]:
    """
    Run generation-based evaluation on the eval split.
    Returns aggregate metrics and per-example results.
    """
    model.eval()
    examples = list(eval_dataset)
    if max_examples and len(examples) > max_examples:
        examples = examples[:max_examples]

    all_results = []
    print(f"\n  Running {desc} inference on {len(examples)} examples...")

    for i, example in enumerate(examples):
        if (i + 1) % 10 == 0:
            print(f"    {i + 1}/{len(examples)}...")

        messages = [
            {"role": "system", "content": SEARCH_REASONER_SYSTEM_PROMPT},
            {"role": "user", "content": f"## Question\n{example['question']}\n\n## Search Results\n{example['search_context']}"},
        ]

        try:
            input_text = tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
        except Exception:
            input_text = tokenizer.apply_chat_template(
                messages, tokenize=False
            )

        inputs = tokenizer(
            input_text, return_tensors="pt", truncation=True, max_length=3072
        ).to(model.device)

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.01,
            do_sample=True,
            top_p=0.95,
        )

        generated_ids = outputs[0][inputs["input_ids"].shape[1]:]
        generated_text = tokenizer.decode(generated_ids, skip_special_tokens=False)

        parsed = parse_model_output(generated_text)
        parsed["expected_answer"] = example.get("parsed_answer", "")
        parsed["answer_correct"] = (
            parsed["parsed_answer"] == parsed["expected_answer"]
            if parsed["parsed_answer"]
            else False
        )
        parsed["question_snippet"] = example["question"][:100]
        parsed["generated_snippet"] = generated_text[:300]
        all_results.append(parsed)

    n = len(all_results)
    metrics = {
        f"inference_eval/json_valid_rate_{desc}": sum(r["json_valid"] for r in all_results) / max(n, 1),
        f"inference_eval/schema_valid_rate_{desc}": sum(r["schema_valid"] for r in all_results) / max(n, 1),
        f"inference_eval/answer_accuracy_{desc}": sum(r["answer_correct"] for r in all_results) / max(n, 1),
        f"inference_eval/think_tag_rate_{desc}": sum(r["has_think_tags"] for r in all_results) / max(n, 1),
        f"inference_eval/n_examples_{desc}": n,
    }

    print(f"\n  ── {desc} Results ({n} examples) ──")
    print(f"    JSON valid rate:    {metrics[f'inference_eval/json_valid_rate_{desc}']:.1%}")
    print(f"    Schema valid rate:  {metrics[f'inference_eval/schema_valid_rate_{desc}']:.1%}")
    print(f"    Answer accuracy:    {metrics[f'inference_eval/answer_accuracy_{desc}']:.1%}")
    print(f"    Think tag rate:     {metrics[f'inference_eval/think_tag_rate_{desc}']:.1%}")

    return metrics, all_results


def log_eval_to_wandb(metrics: dict, per_example: list[dict], phase: str):
    """Log eval results to W&B with tables."""
    import wandb

    wandb.log(metrics)

    table = wandb.Table(
        columns=[
            "idx", "question", "json_valid", "schema_valid",
            "parsed_answer", "expected_answer", "correct", "generated_snippet",
        ]
    )
    for i, r in enumerate(per_example):
        table.add_data(
            i,
            r.get("question_snippet", ""),
            r["json_valid"],
            r["schema_valid"],
            r.get("parsed_answer", ""),
            r.get("expected_answer", ""),
            r.get("answer_correct", False),
            r.get("generated_snippet", ""),
        )
    wandb.log({f"{phase}/per_example_results": table})


# ──────────────────────────────────────────────
# 5. W&B RICH LOGGING
# ──────────────────────────────────────────────


def log_dataset_analysis(train_dataset, eval_dataset, tokenizer, response_template: str):
    """Log dataset stats to W&B at init."""
    import wandb

    train_lengths = [len(tokenizer.encode(x["text"])) for x in train_dataset]
    eval_lengths = [len(tokenizer.encode(x["text"])) for x in eval_dataset]

    input_token_counts = []
    target_token_counts = []
    for example in train_dataset:
        text = example["text"]
        idx = text.find(response_template)
        if idx >= 0:
            input_part = text[:idx + len(response_template)]
            target_part = text[idx + len(response_template):]
            input_token_counts.append(len(tokenizer.encode(input_part)))
            target_token_counts.append(len(tokenizer.encode(target_part)))
        else:
            input_token_counts.append(len(tokenizer.encode(text)))
            target_token_counts.append(0)

    wandb.log({
        "dataset/train_size": len(train_dataset),
        "dataset/eval_size": len(eval_dataset),
        "dataset/train_token_lengths": wandb.Histogram(train_lengths, num_bins=50),
        "dataset/eval_token_lengths": wandb.Histogram(eval_lengths, num_bins=50),
        "dataset/train_mean_tokens": np.mean(train_lengths),
        "dataset/train_median_tokens": np.median(train_lengths),
        "dataset/train_max_tokens": max(train_lengths),
        "dataset/train_min_tokens": min(train_lengths),
        "dataset/avg_input_tokens": np.mean(input_token_counts),
        "dataset/avg_target_tokens": np.mean(target_token_counts),
        "dataset/train_total_tokens": sum(train_lengths),
    })

    sample_table = wandb.Table(
        columns=["idx", "question_snippet", "answer", "n_tokens"]
    )
    for i, example in enumerate(train_dataset):
        if i >= 20:
            break
        q = example.get("question", "")[:150] if isinstance(example, dict) else ""
        a = example.get("parsed_answer", "") if isinstance(example, dict) else ""
        n = train_lengths[i] if i < len(train_lengths) else 0
        sample_table.add_data(i, q, a, n)
    wandb.log({"dataset/sample_examples": sample_table})


class WandbRichCallback(TrainerCallback):
    """
    Custom callback for rich W&B logging during training.
    Tracks gradients, LoRA weights, GPU utilization, and performance.
    """

    def __init__(self, model, tokenizer, log_grad_every_n=10):
        self.model = model
        self.tokenizer = tokenizer
        self.log_grad_every_n = log_grad_every_n
        self.step_times = []
        self.last_step_time = None
        self.training_start_time = None

    def on_train_begin(self, args, state, control, **kwargs):
        self.training_start_time = time.time()
        self.last_step_time = time.time()

        import wandb

        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(
            p.numel() for p in self.model.parameters() if p.requires_grad
        )

        wandb.log({
            "model/total_params_M": total_params / 1e6,
            "model/trainable_params_M": trainable_params / 1e6,
            "model/trainable_params": trainable_params,
            "model/trainable_percent": 100 * trainable_params / total_params,
        })

        lora_layers = []
        for name, param in self.model.named_parameters():
            if param.requires_grad and "lora" in name.lower():
                lora_layers.append(
                    [name, list(param.shape), param.numel(), f"{param.dtype}"]
                )

        if lora_layers:
            lora_table = wandb.Table(
                columns=["layer_name", "shape", "params", "dtype"], data=lora_layers
            )
            wandb.log({"model/lora_layers": lora_table})

        if torch.cuda.is_available():
            for i in range(torch.cuda.device_count()):
                props = torch.cuda.get_device_properties(i)
                total_mem = getattr(props, "total_memory", None) or getattr(props, "total_mem", 0)
                wandb.log({
                    f"system/gpu_{i}_name": props.name,
                    f"system/gpu_{i}_vram_GB": total_mem / 1e9,
                })

    def on_step_end(self, args, state: TrainerState, control, **kwargs):
        import wandb

        now = time.time()
        step_time = now - self.last_step_time
        self.last_step_time = now
        self.step_times.append(step_time)

        step = state.global_step
        logs = {}

        logs["perf/step_time_seconds"] = step_time
        logs["perf/steps_per_second"] = 1.0 / max(step_time, 1e-6)
        if len(self.step_times) > 1:
            logs["perf/avg_step_time"] = np.mean(self.step_times[-50:])
            logs["perf/rolling_steps_per_sec"] = 1.0 / np.mean(self.step_times[-50:])

        elapsed = now - self.training_start_time
        logs["perf/elapsed_minutes"] = elapsed / 60
        if state.max_steps > 0:
            remaining_steps = state.max_steps - step
            est_remaining = remaining_steps * np.mean(self.step_times[-50:])
            logs["perf/eta_minutes"] = est_remaining / 60
            logs["perf/progress_pct"] = 100 * step / state.max_steps

        if torch.cuda.is_available():
            for i in range(torch.cuda.device_count()):
                mem_alloc = torch.cuda.memory_allocated(i) / 1e9
                mem_reserved = torch.cuda.memory_reserved(i) / 1e9
                _props = torch.cuda.get_device_properties(i)
                mem_total = (getattr(_props, "total_memory", None) or getattr(_props, "total_mem", 0)) / 1e9
                logs[f"gpu/gpu_{i}_allocated_GB"] = mem_alloc
                logs[f"gpu/gpu_{i}_reserved_GB"] = mem_reserved
                logs[f"gpu/gpu_{i}_utilization_pct"] = 100 * mem_alloc / mem_total

        if step % self.log_grad_every_n == 0:
            grad_norms = {}
            lora_A_norms = {}
            lora_B_norms = {}
            all_grad_norms = []

            for name, param in self.model.named_parameters():
                if param.requires_grad and param.grad is not None:
                    grad_norm = param.grad.data.norm(2).item()
                    all_grad_norms.append(grad_norm)

                    for module_type in [
                        "q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj",
                    ]:
                        if module_type in name:
                            key = f"gradients/{module_type}"
                            if key not in grad_norms:
                                grad_norms[key] = []
                            grad_norms[key].append(grad_norm)

                    if "lora_A" in name:
                        for mod in ["q_proj", "k_proj", "v_proj", "o_proj",
                                     "gate_proj", "up_proj", "down_proj"]:
                            if mod in name:
                                lora_A_norms[mod] = param.data.norm(2).item()
                    elif "lora_B" in name:
                        for mod in ["q_proj", "k_proj", "v_proj", "o_proj",
                                     "gate_proj", "up_proj", "down_proj"]:
                            if mod in name:
                                lora_B_norms[mod] = param.data.norm(2).item()

            if all_grad_norms:
                logs["gradients/global_norm"] = np.sqrt(sum(g**2 for g in all_grad_norms))
                logs["gradients/mean_norm"] = np.mean(all_grad_norms)
                logs["gradients/max_norm"] = max(all_grad_norms)
                logs["gradients/min_norm"] = min(all_grad_norms)

            for key, norms in grad_norms.items():
                logs[f"{key}_mean"] = np.mean(norms)
                logs[f"{key}_max"] = max(norms)

            for mod in lora_A_norms:
                if mod in lora_B_norms:
                    logs[f"lora_weights/{mod}_A_norm"] = lora_A_norms[mod]
                    logs[f"lora_weights/{mod}_B_norm"] = lora_B_norms[mod]
                    logs[f"lora_weights/{mod}_effective_norm"] = (
                        lora_A_norms[mod] * lora_B_norms[mod]
                    )

        wandb.log(logs, step=step)

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        import wandb

        if metrics:
            eval_logs = {}
            for k, v in metrics.items():
                clean_key = k.replace("eval_", "eval/")
                eval_logs[clean_key] = v
            if "eval_loss" in metrics:
                eval_logs["eval/perplexity"] = math.exp(min(metrics["eval_loss"], 20))
            wandb.log(eval_logs, step=state.global_step)

    def on_log(self, args, state, control, logs=None, **kwargs):
        import wandb

        if logs is None:
            return
        enhanced = {}
        if "loss" in logs:
            enhanced["train/perplexity"] = math.exp(min(logs["loss"], 20))
        if "learning_rate" in logs:
            enhanced["train/lr_log10"] = math.log10(max(logs["learning_rate"], 1e-10))
        enhanced["train/effective_batch_size"] = (
            args.per_device_train_batch_size
            * args.gradient_accumulation_steps
            * max(1, getattr(args, "world_size", 1))
        )
        if enhanced:
            wandb.log(enhanced, step=state.global_step)

    def on_train_end(self, args, state, control, **kwargs):
        import wandb

        total_time = time.time() - self.training_start_time
        wandb.log({
            "summary/total_training_minutes": total_time / 60,
            "summary/total_steps": state.global_step,
            "summary/avg_step_time": np.mean(self.step_times) if self.step_times else 0,
            "summary/final_train_loss": (
                state.log_history[-1].get("loss", 0) if state.log_history else 0
            ),
            "summary/best_eval_loss": min(
                (h.get("eval_loss", float("inf")) for h in state.log_history),
                default=0,
            ),
        })

        if self.step_times:
            wandb.log({
                "summary/step_time_histogram": wandb.Histogram(
                    self.step_times, num_bins=30
                )
            })


def init_wandb(args, model, tokenizer, train_dataset, eval_dataset, response_template):
    """Initialize W&B run with comprehensive config."""
    import wandb

    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

    config = {
        "model_name": args.model_name,
        "model_params_M": total_params / 1e6,
        "trainable_params_M": trainable_params / 1e6,
        "trainable_pct": 100 * trainable_params / total_params,
        "lora/rank": args.lora_r,
        "lora/alpha": args.lora_alpha,
        "lora_dropout": args.lora_dropout,
        "rslora": True,
        "rslora_scaling": args.lora_alpha / (args.lora_r ** 0.5),
        "lora_target_modules": "q,k,v,o,gate,up,down",
        "epochs": args.epochs,
        "learning_rate": args.lr,
        "lr_scheduler": "cosine",
        "batch_size": args.batch_size,
        "gradient_accumulation_steps": args.grad_accum,
        "effective_batch_size": args.batch_size * args.grad_accum,
        "max_length": args.max_length,
        "warmup_ratio": 0.05,
        "weight_decay": 0.01,
        "bf16": True,
        "gradient_checkpointing": True,
        "packing": False,
        "dataset": args.dataset,
        "train_examples": len(train_dataset),
        "eval_examples": len(eval_dataset),
        "completion_only_masking": True,
        "gpu_count": torch.cuda.device_count() if torch.cuda.is_available() else 0,
        "gpu_name": (
            torch.cuda.get_device_name(0) if torch.cuda.is_available() else "N/A"
        ),
    }

    wandb.init(
        project=args.wandb_project,
        name=args.wandb_run_name or f"search-reasoner-3b-r{args.lora_r}-e{args.epochs}",
        config=config,
        tags=[
            "sft", "ministral-3b", "search-reasoner", "cot",
            f"lora-r{args.lora_r}", "rslora", "completion-masking", "hackathon",
        ],
    )

    print("\n  Logging dataset analysis to W&B...")
    log_dataset_analysis(train_dataset, eval_dataset, tokenizer, response_template)

    return wandb.run


# ──────────────────────────────────────────────
# 6. MAIN TRAINING LOOP
# ──────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="SFT training for Search Reasoner (Ministral-3B)"
    )
    parser.add_argument(
        "--model_name", type=str,
        default="mistralai/Ministral-3-3B-Instruct-2512-BF16",
    )
    parser.add_argument(
        "--dataset", type=str,
        default="outputs/cot_training_data.jsonl",
    )
    parser.add_argument(
        "--output_dir", type=str,
        default="./search-reasoner-3b-sft",
    )
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--grad_accum", type=int, default=16)
    parser.add_argument("--max_length", type=int, default=6144)
    parser.add_argument("--lora_r", type=int, default=64)
    parser.add_argument("--lora_alpha", type=int, default=128)
    parser.add_argument("--lora_dropout", type=float, default=0.05)
    parser.add_argument(
        "--hub_repo", type=str, default=None,
        help="HuggingFace Hub repo (e.g. 'user/search-reasoner-3b')",
    )
    parser.add_argument("--hub_private", action="store_true", default=False)
    parser.add_argument(
        "--wandb_project", type=str, default="search-reasoner-3b",
    )
    parser.add_argument("--wandb_run_name", type=str, default=None)
    parser.add_argument("--no_wandb", action="store_true", default=False)
    parser.add_argument("--eval_max_examples", type=int, default=50)
    parser.add_argument("--skip_eval", action="store_true", default=False)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--hf_token", type=str, default=None,
        help="HuggingFace access token (or HF_TOKEN env var)",
    )
    parser.add_argument(
        "--wandb_key", type=str, default=None,
        help="Weights & Biases API key (or WANDB_API_KEY env var)",
    )
    args = parser.parse_args()

    # ── Authenticate services ──
    hf_token = args.hf_token or os.environ.get("HF_TOKEN")
    if hf_token:
        os.environ["HF_TOKEN"] = hf_token
        from huggingface_hub import login as hf_login
        hf_login(token=hf_token, add_to_git_credential=False)
        print("  HuggingFace: authenticated")

    wandb_key = args.wandb_key or os.environ.get("WANDB_API_KEY")
    if wandb_key:
        os.environ["WANDB_API_KEY"] = wandb_key
        print("  W&B: API key set")

    print("=" * 60)
    print("Search Reasoner SFT Training")
    print("=" * 60)
    print(f"Model:    {args.model_name}")
    print(f"Dataset:  {args.dataset}")
    print(f"LoRA:     r={args.lora_r}, alpha={args.lora_alpha}, rslora")
    print(f"Epochs:   {args.epochs}")
    print(f"LR:       {args.lr}")
    print(f"Batch:    {args.batch_size} x {args.grad_accum} accum")
    print(f"Max Seq:  {args.max_length}")
    print("=" * 60)

    # ── Load tokenizer ──
    print("\n[1/6] Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # ── Load and format dataset ──
    print("\n[2/6] Loading and formatting dataset...")
    raw_dataset = load_cot_dataset(args.dataset)

    split = raw_dataset.train_test_split(test_size=0.1, seed=args.seed)
    raw_train = split["train"]
    raw_eval = split["test"]
    print(f"  Train: {len(raw_train)}, Eval: {len(raw_eval)}")

    train_dataset = raw_train.map(format_to_messages, desc="Formatting train")
    eval_dataset = raw_eval.map(format_to_messages, desc="Formatting eval")

    train_dataset = train_dataset.map(
        lambda x: apply_chat_template(x, tokenizer),
        desc="Applying chat template (train)",
    )
    eval_dataset = eval_dataset.map(
        lambda x: apply_chat_template(x, tokenizer),
        desc="Applying chat template (eval)",
    )

    print("\n── Sample formatted text (first 500 chars) ──")
    print(train_dataset[0]["text"][:500])
    print("...")

    train_lengths = [len(tokenizer.encode(x["text"])) for x in train_dataset]
    print(f"\nToken lengths — mean: {np.mean(train_lengths):.0f}, "
          f"max: {max(train_lengths)}, min: {min(train_lengths)}")

    n_before = len(train_dataset)
    train_dataset = train_dataset.filter(
        lambda x: len(tokenizer.encode(x["text"])) <= args.max_length
    )
    eval_dataset = eval_dataset.filter(
        lambda x: len(tokenizer.encode(x["text"])) <= args.max_length
    )
    n_filtered = n_before - len(train_dataset)
    truncation_rate = n_filtered / max(n_before, 1)
    if n_filtered > 0:
        print(f"Filtered {n_filtered} train examples exceeding {args.max_length} tokens "
              f"({truncation_rate:.1%})")

    # ── Load model ──
    print("\n[3/6] Loading model...")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    model_cls = AutoModelForCausalLM
    if _MINISTRAL_CLS is not None and "Ministral" in args.model_name:
        model_cls = _MINISTRAL_CLS
        print(f"  Using explicit class: {model_cls.__name__}")

    model = model_cls.from_pretrained(
        args.model_name,
        quantization_config=bnb_config,
        trust_remote_code=True,
        dtype=torch.bfloat16,
        device_map="auto",
    )
    model.gradient_checkpointing_enable()

    # ── Setup LoRA ──
    print("\n[3.5/6] Setting up LoRA...")
    peft_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        use_rslora=True,
    )
    print(f"  rsLoRA: scaling = alpha/sqrt(r) = {args.lora_alpha}/{args.lora_r**0.5:.1f} "
          f"= {args.lora_alpha / args.lora_r**0.5:.2f}")

    # ── Completion-only loss masking ──
    print("\n[3.5b/6] Setting up completion-only loss masking...")
    response_template = detect_response_template(tokenizer)
    print(f"  Detected response template: {repr(response_template)}")

    data_collator = None
    use_completion_only_config = False

    if _HAS_COMPLETION_COLLATOR:
        response_template_ids = tokenizer.encode(
            response_template, add_special_tokens=False
        )
        print(f"  Response template token IDs: {response_template_ids}")
        decoded_back = tokenizer.decode(response_template_ids)
        print(f"  Decoded back: {repr(decoded_back)}")
        data_collator = DataCollatorForCompletionOnlyLM(
            response_template=response_template_ids, tokenizer=tokenizer
        )
        print("  Using DataCollatorForCompletionOnlyLM")
    else:
        use_completion_only_config = True
        print("  Using SFTConfig completion_only_loss=True (trl >= 0.29)")

    # ── Training arguments ──
    print("\n[4/6] Setting up training...")
    sft_kwargs = dict(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        weight_decay=0.01,
        bf16=True,
        logging_steps=10,
        save_steps=50,
        save_total_limit=3,
        eval_strategy="steps",
        eval_steps=50,
        seed=args.seed,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        max_length=args.max_length,
        dataset_text_field="text",
        report_to="none" if args.no_wandb else "wandb",
        packing=False,
    )
    if use_completion_only_config:
        sft_kwargs["completion_only_loss"] = True
    training_args = SFTConfig(**sft_kwargs)

    # ── Initialize W&B ──
    wandb_callback = None
    if not args.no_wandb:
        print("\n[4.5/6] Initializing Weights & Biases...")
        init_wandb(
            args, model, tokenizer, train_dataset, eval_dataset, response_template
        )

        import wandb
        wandb.log({
            "lora/rank": args.lora_r,
            "lora/alpha": args.lora_alpha,
            "dataset/truncation_rate": truncation_rate,
        })

        wandb_callback = WandbRichCallback(model, tokenizer, log_grad_every_n=5)

    # ── Create trainer ──
    callbacks = [wandb_callback] if wandb_callback else []
    trainer_kwargs = dict(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        processing_class=tokenizer,
        peft_config=peft_config,
        callbacks=callbacks,
    )
    if data_collator is not None:
        trainer_kwargs["data_collator"] = data_collator
    trainer = SFTTrainer(**trainer_kwargs)

    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"Trainable params: {trainable:,} / {total:,} ({100 * trainable / total:.2f}%)")

    # ── Pre-training eval (baseline) ──
    pre_eval_metrics = None
    if not args.skip_eval:
        print("\n[4.8/6] Running PRE-TRAINING inference eval (baseline)...")
        pre_eval_metrics, pre_eval_examples = run_inference_eval(
            trainer.model, tokenizer, raw_eval,
            max_examples=args.eval_max_examples,
            desc="base",
        )
        if not args.no_wandb:
            log_eval_to_wandb(pre_eval_metrics, pre_eval_examples, "pre_train_eval")

    # ── Train ──
    print("\n[5/6] Starting training...")
    trainer.train()

    # ── Save ──
    print("\n[6/6] Saving model...")
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)

    print("Merging LoRA weights and saving full model...")
    merged_dir = args.output_dir + "-merged"
    merged_model = trainer.model.merge_and_unload()
    merged_model.save_pretrained(merged_dir)
    tokenizer.save_pretrained(merged_dir)
    print(f"Merged model saved to: {merged_dir}")

    # ── Post-training eval ──
    post_eval_metrics = None
    if not args.skip_eval:
        print("\n[POST] Running POST-TRAINING inference eval...")
        post_eval_metrics, post_eval_examples = run_inference_eval(
            trainer.model, tokenizer, raw_eval,
            max_examples=args.eval_max_examples,
            desc="finetuned",
        )
        if not args.no_wandb:
            log_eval_to_wandb(post_eval_metrics, post_eval_examples, "post_train_eval")

        # Comparison
        if pre_eval_metrics and post_eval_metrics:
            print("\n  ══════════════════════════════════════════════")
            print("  PRE vs POST TRAINING COMPARISON")
            print("  ══════════════════════════════════════════════")

            comparison_data = []
            metric_pairs = [
                ("json_valid_rate", "inference_eval/json_valid_rate_base", "inference_eval/json_valid_rate_finetuned"),
                ("schema_valid_rate", "inference_eval/schema_valid_rate_base", "inference_eval/schema_valid_rate_finetuned"),
                ("answer_accuracy", "inference_eval/answer_accuracy_base", "inference_eval/answer_accuracy_finetuned"),
                ("think_tag_rate", "inference_eval/think_tag_rate_base", "inference_eval/think_tag_rate_finetuned"),
            ]
            for name, pre_key, post_key in metric_pairs:
                pre_val = pre_eval_metrics.get(pre_key, 0)
                post_val = post_eval_metrics.get(post_key, 0)
                delta = post_val - pre_val
                delta_str = f"+{delta:.1%}" if delta >= 0 else f"{delta:.1%}"
                print(f"    {name:<25s}  {pre_val:.1%} -> {post_val:.1%}  ({delta_str})")
                comparison_data.append([
                    name,
                    round(pre_val * 100, 1),
                    round(post_val * 100, 1),
                    round(delta * 100, 1),
                ])

            if not args.no_wandb:
                import wandb

                comparison_table = wandb.Table(
                    columns=["metric", "pre_train_%", "post_train_%", "delta_%"],
                    data=comparison_data,
                )
                wandb.log({"eval_comparison/summary": comparison_table})

                delta_accuracy = (
                    post_eval_metrics.get("inference_eval/answer_accuracy_finetuned", 0)
                    - pre_eval_metrics.get("inference_eval/answer_accuracy_base", 0)
                )
                wandb.log({
                    "inference_eval/delta_answer_accuracy": delta_accuracy,
                    "inference_eval/json_valid_rate_base": pre_eval_metrics.get("inference_eval/json_valid_rate_base", 0),
                    "inference_eval/json_valid_rate_finetuned": post_eval_metrics.get("inference_eval/json_valid_rate_finetuned", 0),
                    "inference_eval/schema_valid_rate_base": pre_eval_metrics.get("inference_eval/schema_valid_rate_base", 0),
                    "inference_eval/schema_valid_rate_finetuned": post_eval_metrics.get("inference_eval/schema_valid_rate_finetuned", 0),
                    "inference_eval/answer_accuracy_base": pre_eval_metrics.get("inference_eval/answer_accuracy_base", 0),
                    "inference_eval/answer_accuracy_finetuned": post_eval_metrics.get("inference_eval/answer_accuracy_finetuned", 0),
                })

    # ── Push to HuggingFace Hub ──
    if args.hub_repo:
        from huggingface_hub import HfApi, create_repo

        print(f"\nPushing to HuggingFace Hub: {args.hub_repo}")
        api = HfApi()

        try:
            create_repo(args.hub_repo, private=args.hub_private, exist_ok=True)
        except Exception as e:
            print(f"  Note: {e}")

        print(f"  Uploading from: {merged_dir}")
        api.upload_folder(
            folder_path=merged_dir,
            repo_id=args.hub_repo,
            commit_message=(
                f"Search Reasoner SFT | rsLoRA r={args.lora_r} | "
                f"{args.epochs} epochs | Ministral-3B"
            ),
        )
        print(f"  Uploaded to https://huggingface.co/{args.hub_repo}")

        lora_repo = args.hub_repo + "-lora"
        try:
            create_repo(lora_repo, private=args.hub_private, exist_ok=True)
            api.upload_folder(
                folder_path=args.output_dir,
                repo_id=lora_repo,
                commit_message=(
                    f"LoRA adapter: rsLoRA r={args.lora_r}, "
                    f"alpha={args.lora_alpha}, {args.epochs} epochs"
                ),
            )
            print(f"  LoRA adapter uploaded to https://huggingface.co/{lora_repo}")
        except Exception as e:
            print(f"  LoRA upload skipped: {e}")

    # ── Finalize ──
    print("\n" + "=" * 60)
    print("Training complete!")
    print(f"Checkpoint: {args.output_dir}")
    print(f"Merged:     {merged_dir}")
    if args.hub_repo:
        print(f"Hub:        https://huggingface.co/{args.hub_repo}")
    print("=" * 60)

    if not args.no_wandb:
        import wandb

        print("\nLogging model artifact to W&B...")
        artifact_dir = merged_dir if os.path.exists(merged_dir) else args.output_dir
        model_artifact = wandb.Artifact(
            name="search-reasoner-3b-sft",
            type="model",
            description=(
                f"Search Reasoner SFT | rsLoRA r={args.lora_r} | "
                f"{args.epochs} epochs"
            ),
            metadata={
                "base_model": args.model_name,
                "dataset": args.dataset,
                "lora_r": args.lora_r,
                "epochs": args.epochs,
                "final_loss": (
                    trainer.state.log_history[-1].get("loss", None)
                    if trainer.state.log_history else None
                ),
                "pre_answer_accuracy": (
                    pre_eval_metrics.get("inference_eval/answer_accuracy_base")
                    if pre_eval_metrics else None
                ),
                "post_answer_accuracy": (
                    post_eval_metrics.get("inference_eval/answer_accuracy_finetuned")
                    if post_eval_metrics else None
                ),
            },
        )
        model_artifact.add_dir(artifact_dir)
        wandb.log_artifact(model_artifact)

        summary_data = [
            ["Base Model", args.model_name],
            ["Dataset", args.dataset],
            ["Train Examples", str(len(train_dataset))],
            ["Eval Examples", str(len(eval_dataset))],
            ["LoRA Rank", str(args.lora_r)],
            ["rsLoRA Scaling", f"{args.lora_alpha / args.lora_r**0.5:.2f}"],
            ["Epochs", str(args.epochs)],
            ["Learning Rate", str(args.lr)],
            ["Effective Batch Size", str(args.batch_size * args.grad_accum)],
            ["Completion Masking", "Yes"],
        ]
        if pre_eval_metrics:
            summary_data.append([
                "Pre-Train Answer Accuracy",
                f"{pre_eval_metrics.get('inference_eval/answer_accuracy_base', 0):.1%}",
            ])
        if post_eval_metrics:
            summary_data.append([
                "Post-Train Answer Accuracy",
                f"{post_eval_metrics.get('inference_eval/answer_accuracy_finetuned', 0):.1%}",
            ])
        if pre_eval_metrics and post_eval_metrics:
            delta = (
                post_eval_metrics.get("inference_eval/answer_accuracy_finetuned", 0)
                - pre_eval_metrics.get("inference_eval/answer_accuracy_base", 0)
            )
            summary_data.append(["Delta Answer Accuracy", f"{delta:+.1%}"])

        summary_table = wandb.Table(columns=["metric", "value"], data=summary_data)
        wandb.log({"summary/training_config": summary_table})
        wandb.finish()
        print("  W&B run finalized")


if __name__ == "__main__":
    main()
